data_path: "/disk/disk_20T/ruxiangyuan/projects/references/llm-icl/data"
cwd: ""  # 项目路径

task: "ner"
text_input: "秦始皇于公元前221年统一了中国，建立了中央集权的封建制度，首都定于陕西省西安市。"
instruction: "请标注实体"
language: "ch"  # ch or en

api_key: ""
openai_api_base: ""
engine: "gpt-3.5-turbo"

zero_shot: False
domain: "general
labels: ["ORG", "PERSON", "LOCATION"]
