
cwd: null
engine: "ChatGPT"
model_id: "gpt-3.5-turbo"
api_key: "sk-7kVvoLKWePIdvvirGUXY80MVqAsofr3f37kqqHUw7Pnmil3u"
base_url: "https://api.chatanywhere.tech/v1"
temperature: 0.3
top_p: 0.9
max_tokens: 300
stop: null
task: "da"
language: "ch"
in_context: true
#instruction: ""
data_path: "data"
text_input: "创立"
domain:
labels: ["人物", "公司"]
#head_entity:
#head_type:
#tail_entity:
#tail_type:
