task: "ner"
text_input: "秦始皇于公元前221年统一了中国，建立了中央集权的封建制度，首都定于陕西省西安市。"
api_key: " sk-7kVvoLKWePIdvvirGUXY80MVqAsofr3f37kqqHUw7Pnmil3u"
engine: "gpt-3.5-turbo"
zero_shot: False
data_path: "/disk/disk_20T/ruxiangyuan/projects/references/llm-icl/data"
language: "ch"
domain: "general"
instruction: "请标注实体"
labels: ["ORG", "PERSON", "LOCATION"]
cwd: "/disk/disk_20T/ruxiangyuan/projects/references/llm-icl"  # 你当前项目的绝对路径
openai_api_base: "https://api.chatanywhere.org/v1"
